export const ap = {
    pageTitle: 'Automation Testing Practice',
    name: 'input[id="name"]',
    email: 'input[id="email"]',
    genderMale: 'input[id="male"]',
    genderFemale: 'input[id="female"]',
    monday: 'input[id="monday"]',
    animals: '//select[@id="animals"]//option',
    country: '//select[@id="country"]',
    uploadFile: 'input[id="singleFileInput"]',
    staticTable: (bookName: string, rowNumb: number) => `//td[text()="${bookName}"]//following-sibling::td[${rowNumb}]`,
    dynamicColumn: (columnName: string) => `//table//th[text()='${columnName}']/preceding-sibling::th`,
    columnValue: (browserName: string, columnIndex: number) => `//table//tr[td[text()='${browserName}']]/td[${columnIndex}]`,
    simpleALert: 'button[id=alertBtn]',
    confirmAlert: 'button[id=confirmBtn]',
    promptAlert: 'button[id=promptBtn]',
    draggable: 'div[id=draggable]',
    droppable: 'div[id=droppable]',
    subject: 'input[name=subject]',
    message: 'textarea[id=message]',
    deleteAccount: '//a[contains(text()," Delete Account")]',
    loggedInAs: '//a[contains(text(),"Logged in as")]',
    accountDeleted: '//b[text()="Account Deleted!"]',
    continueButton: '//a[text()="Continue"]',
    logout: '//a[contains(text(),"Logout")]',
    contactUs: '//a[text()=" Contact us"]',
    fileInput: 'input[type="file"]',
    // submitButton: 'input[name=submit]',
    submitButton: 'button#Submit',
    successMessage: '//div[contains(text(),"Your details have been submitted")]'
}